language: php
php:
    - 7.4

before_script:
    - composer self-update
    - composer install --optimize-autoloader --prefer-dist --no-interaction --no-progress --no-suggest

script:
    - vendor/bin/robo --no-interaction code:cs --strict
    - vendor/bin/phpcs -p --ignore=vendor --standard=vendor/glpi-project/coding-standard/GlpiStandard/ .

cache:
    directories:
          - $HOME/.composer/cache
